AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  HelloWorldApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: 'Prod'
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: 'HelloWorldApi'
          version: '1.0.0'
        paths:
          /hello:
            get:
              responses:
                '200':
                  description: 'Successful response'
                  headers:
                    Access-Control-Allow-Origin:
                        type: string
                  content:
                    application/json:
                      example:
                        message: 'Hello, World!'
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
                passthroughBehavior: 'when_no_match'
                httpMethod: 'POST'
                type: 'aws_proxy'
                default:
                  statusCode: 200
                  responseParameters:
                    method.response.header.Access-Control-Allow-Origin : "'*'"

  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ./src
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /hello
            Method: get

Outputs:
  HelloWorldApiUrl:
    Description: 'URL of the HelloWorldApi endpoint'
    Value: !Sub 'https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
