version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: application
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - my-network

networks:
  my-network:
